### ISSUE TITLE
An error appeared when writing output: IndexError: list index out of range

### ISSUE THREAD

**Issue by hugangao** [mmongiacmu/AdenPredictor#2]
Hi AdenPredictor developer

Thanks for developing the tool for the community.
I got an error when using AdenPredictor on my A-domain sequences in Fasta format, and I could get the result TSV file which seems to be incomplete. But it works well on your provided example sequence. Here is the detail about the error:

Absolute path /media/hh/4E54CDCE54CDB94B/AdenPredictor/Indole_diketopiperazine-NRPS.fasta
No -k option provided, resorting to default value 1
We will extract hmmpfam2 output from /media/hh/4E54CDCE54CDB94B/AdenPredictor/Indole_diketopiperazine-NRPS.fasta
We have extracted hmmpfam2 output

Test Data Analysis
Writing output in ./test.tsv
Traceback (most recent call last):
  File "/media/hh/4E54CDCE54CDB94B/AdenPredictor/src/AdenPredictor/helper/helper.py", line 463, in <module>
    main(sys.argv[1:])
  File "/media/hh/4E54CDCE54CDB94B/AdenPredictor/src/AdenPredictor/helper/helper.py", line 459, in main
    get_pred_from_hmmpfam_output(test_hmmpfam_file_name, k, train_hmmpfam_file_name=train_hmmpfam_file_name, sig=s, outfile=outfile, log_train=False, log_test=True)
  File "/media/hh/4E54CDCE54CDB94B/AdenPredictor/src/AdenPredictor/helper/helper.py", line 400, in get_pred_from_hmmpfam_output
    writer.writerow(dict(zip(fieldnames, [v[0], v[1]] + test_pred_final[i])))
                                                                 ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

I have confirmed this sequence will cause the error.
AQAMQQPSRQAVSAWDGGFTYGELAHLSSNFARLLSLFAVGRGSFVPICMDKSRWAVVSILAVLQAGATCVLLDPQYPRQRMKDIITGLSVPVLVNAPSTAPVTRGLSAIQLCVSAKFTEQLWTSNPSGSHFQAHVDPDDLAFVIFTSGSTGAPKGIAMPHSTISSSIRHNSAAMRFDADTRTLHFSSYAFDVSIYEIFTTLASGGCVCVPSEFQRTNELADFIQQWRVNWAFLTPSTAQSLHPSEVPGLATLVLGGEAVTPDHVEVWAPGRTLINGYGPAEATICAVGPLPEHGWVPGKIGHVVGGVGWVTVPSDPNRLAAIGAIGELLLEGPFLARGYLNQHEATAASFITPPPWRRKLLPGCDADTTRLYRTGDLVRYQEDGSLRYIGRRDTQVKVR
Does AdenPredictor have any special requirements for input sequence?

**Comment by wLab-wzu** [comment]
I also have this problem, any solution?

**Comment by hasaiki136** [comment]
The same problem, how to solve it?

**Comment by hasaiki136** [comment]
> The same problem, how to solve it?

I found a logical loophole in the code of Adenpredictor, which can only produce complete output on the dataset provided by them. Here，‘s’ is not always in 'train_sig_sub_dict_orig'，this will lead to the problem.
![Snipaste_2024-11-14_21-30-47](https://github.com/user-attachments/assets/16a3ea31-de20-4e49-b8cb-cffe025d64ed)
